apiVersion: apps/v1
kind: Deployment
metadata:
  name: uselessapp
  labels:
    app: uselessapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uselessapp
  template:
    metadata:
      labels:
        app: uselessapp
    spec:
      containers:
        - name: uselessapp
          image: sha256:39afff5d2968174e369e84daa06395ef43ca78ee5a37ba94040bfdddaff218c8
          ports:
            - containerPort: 80
